// ─── House of Nanda — Database Seeder ────────────────────────────────────────
// Run: npx ts-node src/database/seed.ts

import 'reflect-metadata';
import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';
dotenv.config();

import { Product } from '../products/product.entity';
import { Category } from '../categories/category.entity';
import { Collection } from '../collections/collection.entity';
import { Testimonial } from '../testimonials/testimonial.entity';
import { Faq } from '../faq/faq.entity';
import { User } from '../users/user.entity';
import { Address } from '../addresses/address.entity';
import { Cart } from '../cart/cart.entity';
import { CartItem } from '../cart/cart-item.entity';
import { WishlistItem } from '../wishlist/wishlist.entity';
import { Order } from '../orders/order.entity';
import { OrderItem } from '../orders/order-item.entity';

const AppDataSource = new DataSource({
  type: 'mysql',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '3306'),
  username: process.env.DB_USERNAME || 'root',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || 'house_of_nanda',
  entities: [Product, Category, Collection, Testimonial, Faq, User, Address, Cart, CartItem, WishlistItem, Order, OrderItem],
  synchronize: true,
});

async function seed() {
  await AppDataSource.initialize();
  console.log('✅ Connected to MySQL');
// Disable foreign key checks
  await AppDataSource.query('SET FOREIGN_KEY_CHECKS = 0');

  // ── Seed Categories ────────────────────────────────────────────────────────
  const categoryRepo = AppDataSource.getRepository(Category);
  await categoryRepo.clear();

  const categories = [
    { name: "Necklaces & Pendants", pahadiName: "हार", slug: "necklaces", count: "140+ Designs", image: "/images/product-aurora-necklace.jpg", gender: "all" },
    { name: "Rings", pahadiName: "अंगूठी", slug: "rings", count: "180+ Designs", image: "/images/cat-rings.jpg", gender: "all" },
    { name: "Earrings", pahadiName: "झुमका", slug: "earrings", count: "200+ Designs", image: "/images/product-jhumka-earrings.jpg", gender: "women" },
    { name: "Bracelets & Bangles", pahadiName: "कड़ा", slug: "bracelets", count: "120+ Designs", image: "/images/product-heritage-bracelet.jpg", gender: "all" },
    { name: "Anklets", pahadiName: "पायल", slug: "anklets", count: "60+ Designs", image: "/images/product-aurora-necklace.jpg", gender: "women" },
    { name: "Maangtika", pahadiName: "माँग टीका", slug: "maangtika", count: "40+ Designs", image: "/images/product-aurora-necklace.jpg", gender: "women" },
    { name: "Mangalsutra", pahadiName: "मंगलसूत्र", slug: "mangalsutra", count: "50+ Designs", image: "/images/collection-silver.jpg", gender: "women" },
    { name: "Men's Rings", pahadiName: "अंगूठी", slug: "men-rings", count: "80+ Designs", image: "/images/product-men-signet-ring.svg", gender: "men" },
    { name: "Chains & Pendants", pahadiName: "चेन", slug: "men-chains", count: "60+ Designs", image: "/images/product-men-box-chain.svg", gender: "men" },
    { name: "Bracelets & Kada", pahadiName: "कड़ा", slug: "men-bracelets", count: "50+ Designs", image: "/images/product-silver-bangle.jpg", gender: "men" },
    { name: "Earrings & Studs", pahadiName: "कान की बाली", slug: "men-earrings", count: "30+ Designs", image: "/images/product-diamond-studs.jpg", gender: "men" },
    { name: "Gold Collection", pahadiName: "सोना", slug: "men-gold", count: "40+ Designs", image: "/images/collection-gold.jpg", gender: "men" },
  ];
  await categoryRepo.save(categoryRepo.create(categories));
  console.log(`✅ Seeded ${categories.length} categories`);

  // ── Seed Collections ───────────────────────────────────────────────────────
  const collectionRepo = AppDataSource.getRepository(Collection);
  await collectionRepo.clear();

  const collections = [
    { id: "gold", badge: "BIS Hallmark", title: "Gold Collection", subtitle: "18KT", desc: "18KT and BIS hallmarked gold jewellery — from everyday studs to statement necklaces.", image: "/images/collection-gold.jpg", cta: "Shop Gold", accent: "18KT Gold", gender: "all" },
    { id: "silver", badge: "925 Sterling", title: "Silver Collection", subtitle: "925 Sterling Silver", desc: "Authentic 925 sterling silver — not plated.", image: "/images/product-aurora-necklace.jpg", cta: "Shop Silver", accent: "925 Sterling Silver", gender: "all" },
    { id: "heritage", badge: "Uttarakhand Heritage", title: "Heritage Collection", subtitle: "Pahadi Craft", desc: "Traditional Uttarakhand jewellery crafted by Pahadi karigars.", image: "/images/product-jhumka-earrings.jpg", cta: "Shop Heritage", accent: "Handcrafted in Uttarakhand", gender: "women" },
    { id: "men", badge: "Men's Edit", title: "Men's Collection", subtitle: "Bold. Minimal. Strong.", desc: "Fine jewellery designed for men.", image: "/images/collection-diamond.jpg", cta: "Shop Men's", accent: "Gold · Silver · Lab Diamonds", gender: "men" },
    { id: "gifting", badge: "Gift Ready", title: "Gift Collection", subtitle: "For Every Occasion", desc: "Curated jewellery sets and gift-ready pieces.", image: "/images/product-aurora-necklace.jpg", cta: "Shop Gifts", accent: "Premium Gift Packaging", gender: "all" },
  ];
  await collectionRepo.save(collectionRepo.create(collections));
  console.log(`✅ Seeded ${collections.length} collections`);

  // ── Seed Products ──────────────────────────────────────────────────────────
  const productRepo = AppDataSource.getRepository(Product);
  await productRepo.clear();

  const products = [
    // Women's Products
    { id: "w1", slug: "ganga-galobandh-necklace", name: "Ganga Galobandh", pahadiName: "गंगा गलोबंद", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "heritage", material: "22KT Gold", badge: "Bestseller", images: ["/images/product-gold-galobandh.svg"], description: "The Galobandh reimagined in 22KT hallmarked gold.", culturalNote: "In Uttarakhand, the Galobandh necklace is passed from mother to daughter across generations.", details: ["22KT BIS Hallmarked Gold", "Weight: 14 grams approx.", "Traditional Garhwali Galobandh form", "Handcrafted by Pahadi karigars", "Certificate of Authenticity included"], inStock: true },
    { id: "w2", slug: "kedarnath-jhumka-earrings", name: "Kedarnath Jhumka", pahadiName: "केदारनाथ झुमका", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "heritage", material: "22KT Gold", badge: "Bestseller", images: ["/images/product-gold-jhumka.svg"], description: "A classic Pahadi jhumka with temple dome silhouette.", culturalNote: "Jhumka earrings are the most beloved everyday ornament in the hills.", details: ["22KT BIS Hallmarked Gold", "Weight: 9.5 grams approx.", "Temple-filigree detailing", "Hook closure with safety catch", "Certificate of Authenticity included"], inStock: true },
    { id: "w3", slug: "himalayan-hansuli-collar", name: "Devidhar Hansuli", pahadiName: "देविधार हंसुली", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "heritage", material: "22KT Gold", badge: "Limited", images: ["/images/product-gold-hansuli.svg"], description: "The Hansuli — a rigid crescent collar — hand-engraved with Mandana geometric patterns.", culturalNote: "The Hansuli was historically gifted by a father to his daughter at marriage.", details: ["22KT BIS Hallmarked Gold", "Weight: 28 grams approx.", "Hand-engraved Mandana motifs", "Screw-clasp with safety lock", "Heirloom gift box included"], inStock: true },
    { id: "w4", slug: "lumina-solitaire-pendant", name: "Nandini Solitaire Pendant", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "gold", material: "Lab Grown Diamond in Gold", badge: "New", images: ["/images/product-gold-nanda-pendant.svg"], description: "An IGI-certified lab grown diamond solitaire pendant on an 18KT gold chain.", details: ["IGI Certified Lab Grown Diamond", "0.5 Carat, VS1 Clarity", "18KT Gold Chain", "Chain length: 16 inches", "IGI Certificate included"], inStock: true },
    { id: "w5", slug: "panchachuli-five-peak-ring", name: "Panchachuli Five-Peak Ring", pahadiName: "पंचाचूली अंगूठी", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "gold", material: "Lab Grown Diamond in Gold", badge: "New", images: ["/images/product-gold-five-peak-ring.svg"], description: "Five IGI-certified lab diamonds set in a ridge formation of 18KT white gold.", culturalNote: "The Panchachuli range holds deep spiritual significance for Kumaon.", details: ["5 IGI Certified Lab Grown Diamonds", "Total carat: 0.75 CT, VVS2 Clarity", "18KT White Gold setting", "Available in sizes 5-12", "IGI Certificate included"], inStock: true, sizes: ["5","6","7","8","9","10","11","12"] },
    { id: "w6", slug: "nanda-devi-solitaire", name: "Nanda Devi Solitaire Ring", pahadiName: "नंदा देवी सॉलिटेयर", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "heritage", material: "Lab Grown Diamond", badge: "Limited", images: ["/images/product-celestial-ring.jpg"], description: "An IGI-certified pear-shaped lab diamond set in 18KT gold.", culturalNote: "Nanda Devi is the presiding deity of Uttarakhand.", details: ["IGI Certified Pear-Cut Lab Diamond", "0.8 Carat, VS1 Clarity", "18KT Gold setting + chain", "Chain length: 18 inches", "IGI Certificate included"], inStock: true },
    { id: "w7", slug: "kumaoni-pahunchi-bangle", name: "Kumaoni Pahunchi Bangle", pahadiName: "कुमाऊँनी पहुंची", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "heritage", material: "925 Silver", badge: "Bestseller", images: ["/images/product-silver-bangle.jpg"], description: "The Pahunchi worn by Kumaoni women at every festival.", culturalNote: "Aipan is a sacred art form made with rice flour and red clay, unique to Kumaon.", details: ["925 Sterling Silver — Oxidised Aipan finish", "Weight: 16 grams approx.", "Inner diameter: 2.5 inches", "Slip-on style", "Certificate of Authenticity included"], inStock: true },
    { id: "w8", slug: "aipan-chandelier-earrings", name: "Aipan Chandelier Earrings", pahadiName: "ऐपण झुमकी", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "heritage", material: "925 Silver", badge: "Trending", images: ["/images/product-silver-chandelier.svg"], description: "Geometric motifs from Kumaoni folk art translated into oxidised silver chandelier earrings.", culturalNote: "Aipan is made only by women in Kumaon, passed mother to daughter for centuries.", details: ["925 Sterling Silver — Oxidised", "Weight: 6.8 grams approx.", "Aipan geometric motifs", "Hook closure", "Certificate of Authenticity included"], inStock: true },
    { id: "w9", slug: "aurora-silver-chain", name: "Mandakini Chain Necklace", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "Trending", images: ["/images/product-silver-arc-necklace.svg"], description: "A minimalist 925 sterling silver chain necklace.", details: ["925 Sterling Silver", "Weight: 5.1 grams approx.", "Chain length: 18 inches", "Lobster clasp closure", "Tarnish-resistant finish"], inStock: true },
    { id: "w10", slug: "celestial-gold-ring", name: "Kailash Gold Ring", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "gold", material: "18KT Gold", badge: "New", images: ["/images/product-celestial-ring.jpg"], description: "An 18KT gold ring featuring delicate star engravings.", details: ["18KT BIS Hallmarked Gold", "Weight: 2.8 grams approx.", "Available in sizes 6-12", "Certificate of Authenticity included", "Free insured delivery"], inStock: true, sizes: ["6","7","8","9","10","11","12"] },
    { id: "w11", slug: "priya-eternity-ring", name: "Satopanth Eternity Band", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "gold", material: "Lab Grown Diamond in Gold", badge: "New", images: ["/images/product-priya-ring.jpg"], description: "An IGI-certified lab grown diamond eternity ring.", details: ["IGI Certified Lab Grown Diamonds", "Total carat: 1.2 CT", "18KT White Gold setting", "Available in sizes 5-10", "IGI Certificate included"], inStock: true, sizes: ["5","6","7","8","9","10"] },
    { id: "w12", slug: "bugyaal-silver-bracelet", name: "Bugyaal Meadow Cuff", pahadiName: "बुग्याल कड़ा", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "heritage", material: "925 Silver", badge: "New", images: ["/images/product-silver-orbit-cuff.svg"], description: "A fluid 925 silver cuff with meadow-flower engravings.", details: ["925 Sterling Silver", "Weight: 10 grams approx.", "Meadow-flower engravings", "Adjustable cuff — fits most wrists", "Certificate of Authenticity included"], inStock: true },
    { id: "w13", slug: "moonfall-drop-earrings", name: "Nainital Drop Earrings", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "Bestseller", images: ["/images/product-moonfall-earrings.jpg"], description: "Elegant 925 sterling silver drop earrings with a crescent moon motif.", details: ["925 Sterling Silver", "Weight: 4.2 grams approx.", "Push-back closure", "Tarnish-resistant coating", "Certificate of Authenticity included"], inStock: true },
    { id: "w14", slug: "diamond-stud-earrings", name: "Tarini Diamond Studs", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "gold", material: "Lab Grown Diamond in Gold", badge: "Bestseller", images: ["/images/product-diamond-studs.jpg"], description: "Classic IGI-certified lab grown diamond stud earrings in 18KT gold.", details: ["IGI Certified Lab Grown Diamonds", "Total carat: 0.8 CT", "18KT Gold setting", "Screw-back closure", "IGI Certificate included"], inStock: true },
    { id: "w15", slug: "pahadi-maangtika-gold", name: "Kumaoni Bridal Maangtika", pahadiName: "कुमाऊँनी माँग टीका", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "heritage", material: "22KT Gold", badge: "New", images: ["/images/product-gold-maangtika.svg"], description: "A traditional Pahadi bridal Maangtika in 22KT BIS hallmarked gold.", culturalNote: "In Uttarakhand, the Maangtika is the first ornament placed on a bride.", details: ["22KT BIS Hallmarked Gold", "Weight: 8 grams approx.", "Adjustable chain length", "Teardrop pendant — hand engraved", "Certificate of Authenticity included"], inStock: true },
    { id: "w16", slug: "contemporary-maangtika-silver", name: "Aipan Silver Maangtika", pahadiName: "ऐपण माँग टीका", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "heritage", material: "925 Silver", badge: "New", images: ["/images/product-silver-maangtika.svg"], description: "A contemporary 925 silver Maangtika with Aipan folk-art engravings.", details: ["925 Sterling Silver — Oxidised finish", "Weight: 4.5 grams approx.", "Adjustable chain length", "Aipan geometric engravings", "Certificate of Authenticity included"], inStock: true },
    { id: "w17", slug: "pahadi-mangalsutra-gold", name: "Devbhoomi Mangalsutra", pahadiName: "देवभूमि मंगलसूत्र", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "heritage", material: "22KT Gold", badge: "Bestseller", images: ["/images/product-gold-mangalsutra.svg"], description: "A sacred Pahadi Mangalsutra in 22KT BIS hallmarked gold.", culturalNote: "In the Himalayan tradition, the Mangalsutra is tied by the groom himself.", details: ["22KT BIS Hallmarked Gold pendant", "Traditional black bead strings", "Chain length: 18 inches", "Kedarnath spire-inspired pendant", "Certificate of Authenticity included"], inStock: true },
    { id: "w18", slug: "modern-mangalsutra-diamond", name: "Nanda Peak Mangalsutra", pahadiName: "नंदा शिखर मंगलसूत्र", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "women", collection: "gold", material: "Lab Grown Diamond in Gold", badge: "New", images: ["/images/product-diamond-mangalsutra.svg"], description: "A modern Mangalsutra with an IGI-certified lab grown diamond solitaire.", details: ["IGI Certified Lab Grown Diamond — 0.3 CT", "18KT Gold chain + pendant", "Chain length: 16 inches — adjustable", "Modern single-chain design", "IGI Certificate included"], inStock: true },
    // Modern Silver Women
    { id: "ws1", slug: "arc-minimal-silver-necklace", name: "Binsar Arc Necklace", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "New", images: ["/images/product-silver-arc-necklace.svg"], description: "A sleek arc pendant on a slim 925 silver chain.", details: ["925 Sterling Silver", "Weight: 3.8 grams", "18-inch adjustable chain", "Tarnish-resistant finish", "Certificate of Authenticity"], inStock: true },
    { id: "ws2", slug: "liquid-stack-ring-set", name: "Trishul Stack Rings", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "Trending", images: ["/images/product-silver-stack-rings.svg"], description: "Three ultra-thin 925 silver rings designed to stack.", details: ["925 Sterling Silver — Set of 3", "Weight: 4.2 grams total", "Available in sizes 5-10", "High-polish finish", "Certificate of Authenticity"], inStock: true, sizes: ["5","6","7","8","9","10"] },
    { id: "ws3", slug: "vertex-bar-silver-earrings", name: "Devidhar Bar Earrings", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "New", images: ["/images/product-silver-bar-earrings.svg"], description: "Clean geometric bar earrings in brushed 925 silver.", details: ["925 Sterling Silver — Brushed finish", "Weight: 3.1 grams", "Push-back stud closure", "35mm drop", "Certificate of Authenticity"], inStock: true },
    { id: "ws4", slug: "orbit-cuff-silver-bracelet", name: "Nanda Orbit Cuff", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "Bestseller", images: ["/images/product-silver-orbit-cuff.svg"], description: "A bold open-ended 925 silver cuff with orbital texture.", details: ["925 Sterling Silver", "Weight: 18 grams", "Open cuff — adjustable fit", "Width: 12mm", "Certificate of Authenticity"], inStock: true },
    { id: "ws5", slug: "horizon-crescent-pendant", name: "Chandra Crescent Pendant", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "New", images: ["/images/product-silver-crescent.svg"], description: "A refined crescent moon pendant on a delicate 925 silver rolo chain.", details: ["925 Sterling Silver", "Weight: 4.5 grams", "16-inch chain + 2-inch extender", "Mirror-polished pendant", "Certificate of Authenticity"], inStock: true },
    { id: "ws6", slug: "chainlink-hoop-earrings", name: "Devbhoomi Hoop Earrings", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "Trending", images: ["/images/product-silver-chainlink-hoops.svg"], description: "Oversized chain-link hoops in 925 sterling silver.", details: ["925 Sterling Silver", "Weight: 5.8 grams", "40mm diameter", "Click-back closure", "Certificate of Authenticity"], inStock: true },
    { id: "ws7", slug: "fluid-link-anklet-silver", name: "Pahadi Payal Anklet", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "New", images: ["/images/product-silver-anklet.svg"], description: "A fluid chain-link 925 silver anklet with a minimalist clasp.", details: ["925 Sterling Silver", "Weight: 5.2 grams", "9.5-inch adjustable", "Lobster clasp", "Certificate of Authenticity"], inStock: true },
    { id: "ws8", slug: "pearl-drop-modern-earrings", name: "Saryu Pearl Drops", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "Bestseller", images: ["/images/product-silver-pearl-drops.svg"], description: "Freshwater pearls suspended from sleek 925 silver bars.", details: ["925 Sterling Silver + Freshwater Pearl", "Weight: 4.8 grams", "28mm drop", "Push-back closure", "Certificate of Authenticity"], inStock: true },
    { id: "ws9", slug: "negative-space-silver-ring", name: "Aakash Open Band Ring", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "New", images: ["/images/product-silver-void-ring.svg"], description: "An architectural open-form ring in 925 silver with cutout negative space design.", details: ["925 Sterling Silver", "Weight: 5.1 grams", "Open adjustable band", "Brushed + polished contrast", "Certificate of Authenticity"], inStock: true, sizes: ["5","6","7","8","9","10"] },
    { id: "ws10", slug: "mesh-silver-bracelet-modern", name: "Kailash Weave Cuff", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women", collection: "silver", material: "925 Silver", badge: "Trending", images: ["/images/product-silver-mesh-bracelet.svg"], description: "A woven mesh 925 silver bracelet with a modern box clasp.", details: ["925 Sterling Silver Mesh", "Weight: 12 grams", "7.5 inch length", "Box clasp with safety", "Certificate of Authenticity"], inStock: true },
    // Men's Products
    { id: "m1", slug: "himalayan-silver-kada", name: "Himalayan Silver Kada", pahadiName: "पर्वत कड़ा", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men", collection: "men", material: "925 Silver", badge: "Bestseller", images: ["/images/product-men-kada.svg"], description: "A bold 925 sterling silver kada bracelet with hammered texture.", culturalNote: "The Kada has deep roots in Uttarakhand warrior tradition.", details: ["925 Sterling Silver — Hammered finish", "Weight: 35 grams approx.", "Inner diameter: 2.6 inches", "Unisex sizing — fits most adult wrists", "Certificate of Authenticity included"], inStock: true },
    { id: "m2", slug: "men-chain-silver-bold", name: "Badrinath Anchor Chain", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men", collection: "men", material: "925 Silver", badge: "New", images: ["/images/product-men-anchor-chain.svg"], description: "A heavy-gauge 925 sterling silver anchor chain.", details: ["925 Sterling Silver", "Weight: 28 grams approx.", "Chain width: 4mm", "Chain length: 22 inches", "Certificate of Authenticity included"], inStock: true },
    { id: "m3", slug: "men-gold-ring-signet", name: "Devta Signet Ring", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "men", collection: "men", material: "22KT Gold", badge: "New", images: ["/images/product-men-signet-ring.svg"], description: "A bold 22KT gold signet ring with Mandana motif engraving.", culturalNote: "Mandana is a sacred geometric folk art of the Kumaon hills.", details: ["22KT BIS Hallmarked Gold", "Weight: 8.5 grams approx.", "Flat signet face — engravable", "Available in sizes 8-14", "Certificate of Authenticity included"], inStock: true, sizes: ["8","9","10","11","12","13","14"] },
    { id: "m4", slug: "men-diamond-pendant", name: "Summit Solitaire Pendant", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "men", collection: "men", material: "Lab Grown Diamond in Gold", badge: "New", images: ["/images/product-men-diamond-pendant.svg"], description: "A single IGI-certified round lab diamond in a brushed 18KT white gold pendant.", details: ["IGI Certified Lab Grown Diamond", "0.5 Carat, VS1 Clarity", "Brushed 18KT White Gold pendant", "Sterling silver chain — 22 inches", "IGI Certificate included"], inStock: true },
    { id: "m5", slug: "men-silver-ring-mountain", name: "Trishul Silver Ring", pahadiName: "त्रिशूल अंगूठी", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men", collection: "men", material: "925 Silver", badge: "Trending", images: ["/images/product-men-trishul-ring.svg"], description: "A wide oxidised silver ring inspired by the Trishul mountain peak.", culturalNote: "Trishul peak is considered sacred in Uttarakhand, the weapon of Mahadev himself.", details: ["925 Sterling Silver — Oxidised finish", "Weight: 6 grams approx.", "Wide band — 8mm width", "Available in sizes 8-14", "Certificate of Authenticity included"], inStock: true, sizes: ["8","9","10","11","12","13","14"] },
    { id: "m6", slug: "men-gold-chain-box", name: "Kedarnath Box Chain", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "men", collection: "men", material: "22KT Gold", badge: "Bestseller", images: ["/images/product-men-curb-gold-chain.svg"], description: "A premium 22KT BIS hallmarked gold box chain.", details: ["22KT BIS Hallmarked Gold", "Weight: 14 grams approx.", "Chain width: 3mm", "Chain length: 22 inches", "Certificate of Authenticity included"], inStock: true },
    { id: "m7", slug: "men-silver-bracelet-link", name: "Altitude Link Bracelet", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men", collection: "men", material: "925 Silver", badge: "Trending", images: ["/images/product-men-link-bracelet.svg"], description: "A heavy-gauge linked 925 silver bracelet.", details: ["925 Sterling Silver", "Weight: 22 grams approx.", "Link width: 10mm", "Length: 8.5 inches with clasp", "Certificate of Authenticity included"], inStock: true },
    { id: "m8", slug: "men-stud-earring-diamond", name: "Shikhar Solitaire Stud", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "men", collection: "men", material: "Lab Grown Diamond in Gold", badge: "New", images: ["/images/product-men-diamond-stud.svg"], description: "A single IGI-certified lab grown diamond stud in 18KT white gold.", details: ["IGI Certified Lab Grown Diamond", "0.25 Carat, VVS1 Clarity", "18KT White Gold push-back stud", "Single earring (one piece)", "IGI Certificate included"], inStock: true },
    { id: "mm1", slug: "onyx-silver-pendant-men", name: "Mahakali Onyx Pendant", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men", collection: "men", material: "925 Silver", badge: "New", images: ["/images/product-men-onyx-pendant.svg"], description: "A matte black onyx stone set in a brushed 925 silver geometric frame.", details: ["925 Sterling Silver — Brushed", "Natural Onyx centre stone", "22-inch sterling silver chain", "Weight: 12 grams", "Certificate of Authenticity"], inStock: true },
    { id: "mm2", slug: "rolo-chain-silver-men", name: "Garhwal Rolo Chain", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men", collection: "men", material: "925 Silver", badge: "Bestseller", images: ["/images/product-men-rolo-chain.svg"], description: "A thick 925 sterling silver rolo chain.", details: ["925 Sterling Silver — High Polish", "Weight: 32 grams", "Chain width: 5mm", "Length: 24 inches", "Certificate of Authenticity"], inStock: true },
    { id: "mm3", slug: "gold-curb-chain-men", name: "Devprayag Gold Chain", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "men", collection: "men", material: "22KT Gold", badge: "Trending", images: ["/images/product-men-curb-gold-chain.svg"], description: "A heavy flat curb chain in 22KT BIS hallmarked gold.", details: ["22KT BIS Hallmarked Gold", "Weight: 18 grams", "Chain width: 4mm", "Length: 22 inches", "Certificate of Authenticity"], inStock: true },
    { id: "mm4", slug: "oxidised-silver-ring-men", name: "Mandakini Shadow Band", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men", collection: "men", material: "925 Silver", badge: "New", images: ["/images/product-men-shadow-ring.svg"], description: "A heavy oxidised 925 silver band with a matte black finish.", details: ["925 Sterling Silver — Oxidised matte", "Weight: 8 grams", "Width: 10mm", "Sizes 8–14", "Certificate of Authenticity"], inStock: true, sizes: ["8","9","10","11","12","13","14"] },
    { id: "mm5", slug: "serpentine-silver-bracelet-men", name: "Nag Serpentine Bracelet", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men", collection: "men", material: "925 Silver", badge: "Trending", images: ["/images/product-men-serpentine-bracelet.svg"], description: "A flat serpentine-link 925 silver bracelet.", details: ["925 Sterling Silver", "Weight: 20 grams", "Width: 8mm", "8-inch length with OT clasp", "Certificate of Authenticity"], inStock: true },
    { id: "mm6", slug: "matte-gold-ring-men", name: "Vishwakarma Forge Band", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "men", collection: "men", material: "22KT Gold", badge: "New", images: ["/images/product-men-forge-ring.svg"], description: "A wide 22KT gold band with a forged matte finish.", details: ["22KT BIS Hallmarked Gold", "Weight: 10 grams", "Width: 7mm", "Sizes 8–14", "Certificate of Authenticity"], inStock: true, sizes: ["8","9","10","11","12","13","14"] },
    { id: "mm7", slug: "lab-diamond-tennis-bracelet-men", name: "Summit Diamond Bracelet", price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "men", collection: "men", material: "Lab Grown Diamond in Gold", badge: "Limited", images: ["/images/product-men-tennis-bracelet.svg"], description: "An IGI-certified lab diamond tennis bracelet in 18KT white gold.", details: ["IGI Certified Lab Grown Diamonds", "Total carat: 2.0 CT", "18KT White Gold setting", "Box clasp with safety", "IGI Certificate included"], inStock: true },
    { id: "mm8", slug: "silver-thread-ring-set-men", name: "Panchachuli Ring Trio", price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men", collection: "men", material: "925 Silver", badge: "New", images: ["/images/product-men-meridian-rings.svg"], description: "Three slim 925 silver rings in varying widths.", details: ["925 Sterling Silver — Set of 3", "Weights: 2g, 4g, 6g", "Sizes 8–14", "Polished + brushed contrast", "Certificate of Authenticity"], inStock: true, sizes: ["8","9","10","11","12","13","14"] },
  ];

  await productRepo.save(productRepo.create(products));
  console.log(`✅ Seeded ${products.length} products`);

  // ── Seed Testimonials ──────────────────────────────────────────────────────
  const testimonialRepo = AppDataSource.getRepository(Testimonial);
  await testimonialRepo.clear();

  const testimonials = [
    { name: "Panchachuli Ring Trio", initial: "P", location: "Dehradun", product: "Ganga Galobandh Necklace", category: "Gold", rating: 5, text: "I wore the Galobandh at my cousin's wedding in Pauri. Every elder in the village recognised the design and asked where I got it. It felt like wearing a piece of my grandmother's memory." },
    { name: "Anjali Bisht", initial: "A", location: "Almora", product: "Kumaoni Pahunchi", category: "Silver", rating: 5, text: "The Aipan patterns on the Pahunchi are exactly what I see on the walls of my family home in Almora during Navratri. This is not a jewelry brand — this is our culture made wearable." },
    { name: "Meenakshi Rawat", initial: "M", location: "Mumbai", product: "Nanda Devi Solitaire", category: "Lab Diamond", rating: 5, text: "Living in Mumbai for 12 years, I sometimes forget where I come from. The Nanda Devi pendant reminds me every day. Extraordinary craftsmanship." },
    { name: "Rohit Chauhan", initial: "R", location: "Delhi", product: "Himalayan Silver Kada", category: "Men's Silver", rating: 5, text: "The Himalayan Kada is unlike anything I've worn before. Heavy, beautiful, and the craftsmanship is visible. Got compliments everywhere." },
    { name: "Vikram Singh", initial: "V", location: "Bengaluru", product: "Devta Signet Ring", category: "Men's Gold", rating: 5, text: "The signet ring is stunning. The gold quality is top notch and the Mandana engraving is so unique — nobody else has anything like this." },
  ];
  await testimonialRepo.save(testimonialRepo.create(testimonials));
  console.log(`✅ Seeded ${testimonials.length} testimonials`);

  // ── Seed FAQs ──────────────────────────────────────────────────────────────
  const faqRepo = AppDataSource.getRepository(Faq);
  await faqRepo.clear();

  const faqs = [
    { category: "Orders & Shipping", question: "How long does delivery take?", answer: "Standard delivery takes 5-7 business days across India. Express delivery (2-3 days) is available at checkout for an additional fee. All orders are fully insured during transit.", sortOrder: 1 },
    { category: "Orders & Shipping", question: "Do you ship internationally?", answer: "Currently we ship only within India. International shipping is coming soon — sign up to our newsletter to be notified.", sortOrder: 2 },
    { category: "Orders & Shipping", question: "Is my order insured during shipping?", answer: "Yes. Every order is 100% insured for its full value during transit. In the rare event of damage or loss, we replace the item at no additional cost.", sortOrder: 3 },
    { category: "Orders & Shipping", question: "Can I track my order?", answer: "Yes. Once your order is dispatched, you'll receive a tracking link via email and SMS.", sortOrder: 4 },
    { category: "Products & Certifications", question: "What does BIS Hallmarked Gold mean?", answer: "BIS (Bureau of Indian Standards) hallmarking is India's official gold purity certification. Our 22KT gold is 91.6% pure and our 18KT is 75% pure.", sortOrder: 1 },
    { category: "Products & Certifications", question: "What is IGI Certified Lab Grown Diamond?", answer: "IGI (International Gemological Institute) is the world's leading diamond certification body. Lab grown diamonds are real diamonds grown in controlled lab environments.", sortOrder: 2 },
    { category: "Products & Certifications", question: "Is your 925 Silver genuine and not plated?", answer: "Yes. All our silver jewellery is solid 925 sterling silver (92.5% pure silver). We never use silver plating.", sortOrder: 3 },
    { category: "Returns & Exchanges", question: "What is your return policy?", answer: "We offer 15-day easy returns on all items. The jewellery must be in its original condition and packaging. Return shipping is free for domestic orders.", sortOrder: 1 },
    { category: "Returns & Exchanges", question: "Can I exchange for a different size?", answer: "Yes. Ring size exchanges are free within 30 days.", sortOrder: 2 },
    { category: "Returns & Exchanges", question: "What if I receive a damaged item?", answer: "Please contact us within 48 hours of delivery with photos of the damage. We'll arrange an immediate replacement or full refund.", sortOrder: 3 },
    { category: "Jewellery Care", question: "How do I care for my gold jewellery?", answer: "Store in the pouch or box provided. Remove before swimming, exercising, or applying perfume/lotion. Clean gently with a soft cloth.", sortOrder: 1 },
    { category: "Jewellery Care", question: "Will my silver jewellery tarnish?", answer: "All 925 silver tarnishes naturally over time — this is normal. Store in an airtight zip-lock bag when not wearing. Clean with a silver polishing cloth.", sortOrder: 2 },
    { category: "Jewellery Care", question: "How do I clean my lab diamond jewellery?", answer: "Soak in warm water with a few drops of mild dish soap, gently scrub with a soft toothbrush, rinse and pat dry.", sortOrder: 3 },
  ];
  await faqRepo.save(faqRepo.create(faqs));
  console.log(`✅ Seeded ${faqs.length} FAQs`);

  await AppDataSource.query('SET FOREIGN_KEY_CHECKS = 1');

  await AppDataSource.destroy();
  console.log('\n🎉 House of Nanda database seeded successfully!');
}

seed().catch((err) => {
  console.error('❌ Seeding failed:', err);
  process.exit(1);
});
