// ─── Types ───────────────────────────────────────────────────────────────────

export interface Product {
  id: string
  slug: string
  name: string
  pahadi_name?: string
  price: number
  originalPrice: number
  discount: number
  category: "gold" | "silver"
  gender: "women" | "men" | "unisex"
  collection: string
  material: string
  badge?: "New" | "Bestseller" | "Limited" | "Trending"
  images: string[]
  description: string
  culturalNote?: string
  details: string[]
  inStock: boolean
  sizes?: string[]
}

export interface Category {
  name: string
  pahadi_name: string
  slug: string
  count: string
  image: string
  gender: "women" | "men" | "all"
}

export interface Collection {
  id: string
  badge: string
  title: string
  subtitle: string
  desc: string
  image: string
  cta: string
  accent: string
  gender: "women" | "men" | "all"
}

// ─── Categories ──────────────────────────────────────────────────────────────

export const categories: Category[] = [
  { name: "Necklaces & Pendants", pahadi_name: "हार", slug: "necklaces", count: "140+ Designs", image: "/images/product-aurora-necklace.jpg", gender: "all" },
  { name: "Rings", pahadi_name: "अंगूठी", slug: "rings", count: "180+ Designs", image: "/images/cat-rings.jpg", gender: "all" },
  { name: "Earrings", pahadi_name: "झुमका", slug: "earrings", count: "200+ Designs", image: "/images/product-jhumka-earrings.jpg", gender: "women" },
  { name: "Bracelets & Bangles", pahadi_name: "कड़ा", slug: "bracelets", count: "120+ Designs", image: "/images/product-heritage-bracelet.jpg", gender: "all" },
  { name: "Anklets", pahadi_name: "पायल", slug: "anklets", count: "60+ Designs", image: "/images/product-aurora-necklace.jpg", gender: "women" },
  { name: "Maangtika", pahadi_name: "माँग टीका", slug: "maangtika", count: "40+ Designs", image: "/images/product-aurora-necklace.jpg", gender: "women" },
  { name: "Mangalsutra", pahadi_name: "मंगलसूत्र", slug: "mangalsutra", count: "50+ Designs", image: "/images/collection-silver.jpg", gender: "women" },
]

export const menCategories: Category[] = [
  { name: "Men's Rings", pahadi_name: "अंगूठी", slug: "men-rings", count: "80+ Designs", image: "/images/product-men-signet-ring.svg", gender: "men" },
  { name: "Chains & Pendants", pahadi_name: "चेन", slug: "men-chains", count: "60+ Designs", image: "/images/product-men-box-chain.svg", gender: "men" },
  { name: "Bracelets & Kada", pahadi_name: "कड़ा", slug: "men-bracelets", count: "50+ Designs", image: "/images/product-silver-bangle.jpg", gender: "men" },
  { name: "Earrings & Studs", pahadi_name: "कान की बाली", slug: "men-earrings", count: "30+ Designs", image: "/images/product-diamond-studs.jpg", gender: "men" },
  { name: "Lab Diamond Men's", pahadi_name: "हीरा", slug: "men-diamonds", count: "25+ Designs", image: "/images/product-diamond-studs.jpg", gender: "men" },
  { name: "Gold Collection", pahadi_name: "सोना", slug: "men-gold", count: "40+ Designs", image: "/images/collection-gold.jpg", gender: "men" },
]

// ─── Collections ─────────────────────────────────────────────────────────────

export const collectionsData: Collection[] = [
  {
    id: "gold",
    badge: "BIS Hallmark",
    title: "Gold Collection",
    subtitle: "18KT",
    desc: "18KT and BIS hallmarked gold jewellery — from everyday studs to statement necklaces. Certified purity, timeless craft.",
    image: "/images/collection-gold.jpg",
    cta: "Shop Gold",
    accent: "18KT Gold",
    gender: "all",
  },
  {
    id: "silver",
    badge: "925 Sterling",
    title: "Silver Collection",
    subtitle: "925 Sterling Silver",
    desc: "Authentic 925 sterling silver — not plated. Minimalist chains, oxidised bangles, and delicate earrings for everyday luxury.",
    image: "/images/product-aurora-necklace.jpg",
    cta: "Shop Silver",
    accent: "925 Sterling Silver",
    gender: "all",
  },

  {
    id: "heritage",
    badge: "Uttarakhand Heritage",
    title: "Heritage Collection",
    subtitle: "Pahadi Craft",
    desc: "Traditional Uttarakhand jewellery — Galobandh, Nathuli, Hansuli, Jhumka — crafted by Pahadi karigars in certified precious metals.",
    image: "/images/product-jhumka-earrings.jpg",
    cta: "Shop Heritage",
    accent: "Handcrafted in Uttarakhand",
    gender: "women",
  },
  {
    id: "men",
    badge: "Men's Edit",
    title: "Men's Collection",
    subtitle: "Bold. Minimal. Strong.",
    desc: "Fine jewellery designed for men — silver chains, gold rings, kada bracelets, and statement pendants. Certified metals, modern design.",
    image: "/images/collection-diamond.jpg",
    cta: "Shop Men's",
    accent: "Gold · Silver · Lab Diamonds",
    gender: "men",
  },
  {
    id: "gifting",
    badge: "Gift Ready",
    title: "Gift Collection",
    subtitle: "For Every Occasion",
    desc: "Curated jewellery sets and gift-ready pieces for birthdays, anniversaries, weddings and festivals. Every order ships in premium gift packaging.",
    image: "/images/product-aurora-necklace.jpg",
    cta: "Shop Gifts",
    accent: "Premium Gift Packaging",
    gender: "all",
  },
]

// ─── Women's Products ─────────────────────────────────────────────────────────

export const womenProducts: Product[] = [
  {
    id: "w1",
    slug: "ganga-galobandh-necklace",
    name: "Ganga Galobandh",
    pahadi_name: "गंगा गलोबंद",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "heritage",
    material: "22KT Gold",
    badge: "Bestseller",
    images: ["/images/product-gold-galobandh.svg"],
    description: "The Galobandh — the most sacred ornament of a Pahadi bride — reimagined in 22KT hallmarked gold. Each bead carries a blessing from the Dev Bhoomi.",
    culturalNote: "In Uttarakhand, the Galobandh necklace is passed from mother to daughter across generations. The layered chain represents the peaks of Kedarnath and Badrinath.",
    details: ["22KT BIS Hallmarked Gold", "Weight: 14 grams approx.", "Traditional Garhwali Galobandh form", "Handcrafted by Pahadi karigars", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "w2",
    slug: "kedarnath-jhumka-earrings",
    name: "Kedarnath Jhumka",
    pahadi_name: "केदारनाथ झुमका",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "heritage",
    material: "22KT Gold",
    badge: "Bestseller",
    images: ["/images/product-gold-jhumka.svg"],
    description: "A classic Pahadi jhumka with temple dome silhouette, inspired by the architecture of Kedarnath shrine. The cascading filigree represents the waterfalls of the holy Mandakini river.",
    culturalNote: "Jhumka earrings are the most beloved everyday ornament in the hills. Designed to swing with the natural gait of a Pahadi woman — the movement itself is considered auspicious.",
    details: ["22KT BIS Hallmarked Gold", "Weight: 9.5 grams approx.", "Temple-filigree detailing", "Hook closure with safety catch", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "w3",
    slug: "himalayan-hansuli-collar",
    name: "Devidhar Hansuli",
    pahadi_name: "देविधार हंसुली",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "heritage",
    material: "22KT Gold",
    badge: "Limited",
    images: ["/images/product-gold-hansuli.svg"],
    description: "The Hansuli — a rigid crescent collar — is the most powerful statement in Pahadi jewellery. Hand-engraved with Mandana geometric patterns.",
    culturalNote: "The Hansuli was historically gifted by a father to his daughter at marriage. Its rigid form symbolises strength, its precious metal symbolises enduring love.",
    details: ["22KT BIS Hallmarked Gold", "Weight: 28 grams approx.", "Hand-engraved Mandana motifs", "Screw-clasp with safety lock", "Heirloom gift box included"],
    inStock: true,
  },
  {
    id: "w4",
    slug: "lumina-solitaire-pendant",
    name: "Nandini Solitaire Pendant",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "gold",
    material: "Lab Grown Diamond in Gold",
    badge: "New",
    images: ["/images/product-gold-nanda-pendant.svg"],
    description: "A breathtaking IGI-certified lab grown diamond solitaire pendant on an 18KT gold chain. Indistinguishable from mined diamonds, at a fraction of the cost.",
    details: ["IGI Certified Lab Grown Diamond", "0.5 Carat, VS1 Clarity", "18KT Gold Chain", "Chain length: 16 inches", "IGI Certificate included"],
    inStock: true,
  },
  {
    id: "w5",
    slug: "panchachuli-five-peak-ring",
    name: "Panchachuli Five-Peak Ring",
    pahadi_name: "पंचाचूली अंगूठी",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "gold",
    material: "Lab Grown Diamond in Gold",
    badge: "New",
    images: ["/images/product-gold-five-peak-ring.svg"],
    description: "Named for the Panchachuli peaks — five snow-clad summits in Pithoragarh — this ring features five IGI-certified lab diamonds set in a ridge formation of 18KT white gold.",
    culturalNote: "The Panchachuli range holds deep spiritual significance for Kumaon. Five diamonds, five peaks, one ring — for those who carry the mountains with them.",
    details: ["5 IGI Certified Lab Grown Diamonds", "Total carat: 0.75 CT, VVS2 Clarity", "18KT White Gold setting", "Available in sizes 5-12", "IGI Certificate included"],
    inStock: true,
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12"],
  },
  {
    id: "w6",
    slug: "nanda-devi-solitaire",
    name: "Nanda Devi Solitaire Ring",
    pahadi_name: "नंदा देवी सॉलिटेयर",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "heritage",
    material: "Lab Grown Diamond",
    badge: "Limited",
    images: ["/images/product-celestial-ring.jpg"],
    description: "Named for Uttarakhand's patron goddess and highest peak. An IGI-certified pear-shaped lab diamond set in 18KT gold — its teardrop form echoes the holy Nanda Devi.",
    culturalNote: "Nanda Devi is the presiding deity of Uttarakhand. To wear this pendant is to carry her blessing.",
    details: ["IGI Certified Pear-Cut Lab Diamond", "0.8 Carat, VS1 Clarity", "18KT Gold setting + chain", "Chain length: 18 inches", "IGI Certificate included"],
    inStock: true,
  },
  {
    id: "w7",
    slug: "kumaoni-pahunchi-bangle",
    name: "Kumaoni Pahunchi Bangle",
    pahadi_name: "कुमाऊँनी पहुंची",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "silver",
    gender: "women",
    collection: "heritage",
    material: "925 Silver",
    badge: "Bestseller",
    images: ["/images/product-silver-bangle.jpg"],
    description: "The Pahunchi is the wrist ornament worn by Kumaoni women at every festival from Harela to Diwali. Oxidised Aipan-inspired patterns — the sacred folk art of Kumaon.",
    culturalNote: "Aipan is a sacred art form made with rice flour and red clay, unique to Kumaon. These devotional patterns are now translated into metal.",
    details: ["925 Sterling Silver — Oxidised Aipan finish", "Weight: 16 grams approx.", "Inner diameter: 2.5 inches", "Slip-on style", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "w8",
    slug: "aipan-chandelier-earrings",
    name: "Aipan Chandelier Earrings",
    pahadi_name: "ऐपण झुमकी",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "silver",
    gender: "women",
    collection: "heritage",
    material: "925 Silver",
    badge: "Trending",
    images: ["/images/product-silver-chandelier.svg"],
    description: "Inspired by the sacred Aipan folk art of Kumaon — geometric motifs found on Kumaoni doorways translated into delicate oxidised silver chandelier earrings.",
    culturalNote: "Aipan is made only by women in Kumaon, passed mother to daughter for centuries. These earrings carry that lineage.",
    details: ["925 Sterling Silver — Oxidised", "Weight: 6.8 grams approx.", "Aipan geometric motifs", "Hook closure", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "w9",
    slug: "aurora-silver-chain",
    name: "Mandakini Chain Necklace",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "silver",
    gender: "women",
    collection: "silver",
    material: "925 Silver",
    badge: "Trending",
    images: ["/images/product-silver-arc-necklace.svg"],
    description: "A minimalist 925 sterling silver chain necklace with a delicate aurora pendant. Effortlessly elegant for everyday wear.",
    details: ["925 Sterling Silver", "Weight: 5.1 grams approx.", "Chain length: 18 inches", "Lobster clasp closure", "Tarnish-resistant finish"],
    inStock: true,
  },
  {
    id: "w10",
    slug: "celestial-gold-ring",
    name: "Kailash Gold Ring",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "gold",
    material: "18KT Gold",
    badge: "New",
    images: ["/images/product-celestial-ring.jpg"],
    description: "An 18KT gold ring featuring delicate star engravings and a fluid loop design. Perfect for those who carry the cosmos on their fingers.",
    details: ["18KT BIS Hallmarked Gold", "Weight: 2.8 grams approx.", "Available in sizes 6-12", "Certificate of Authenticity included", "Free insured delivery"],
    inStock: true,
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
  },
  {
    id: "w11",
    slug: "priya-eternity-ring",
    name: "Satopanth Eternity Band",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "gold",
    material: "Lab Grown Diamond in Gold",
    badge: "New",
    images: ["/images/product-priya-ring.jpg"],
    description: "An IGI-certified lab grown diamond eternity ring set in 18KT white gold. Symbolises infinite love with brilliant sparkle all around.",
    details: ["IGI Certified Lab Grown Diamonds", "Total carat: 1.2 CT", "18KT White Gold setting", "Available in sizes 5-10", "IGI Certificate included"],
    inStock: true,
    sizes: ["5", "6", "7", "8", "9", "10"],
  },
  {
    id: "w12",
    slug: "bugyaal-silver-bracelet",
    name: "Bugyaal Meadow Cuff",
    pahadi_name: "बुग्याल कड़ा",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "silver",
    gender: "women",
    collection: "heritage",
    material: "925 Silver",
    badge: "New",
    images: ["/images/product-silver-orbit-cuff.svg"],
    description: "Named after the alpine meadows of Uttarakhand — a fluid 925 silver cuff with meadow-flower engravings. Light as air, strong as the mountains.",
    details: ["925 Sterling Silver", "Weight: 10 grams approx.", "Meadow-flower engravings", "Adjustable cuff — fits most wrists", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "w13",
    slug: "moonfall-drop-earrings",
    name: "Nainital Drop Earrings",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "silver",
    gender: "women",
    collection: "silver",
    material: "925 Silver",
    badge: "Bestseller",
    images: ["/images/product-moonfall-earrings.jpg"],
    description: "Elegant 925 sterling silver drop earrings with a crescent moon motif. Lightweight, tarnish-resistant, and perfect for everyday luxury.",
    details: ["925 Sterling Silver", "Weight: 4.2 grams approx.", "Push-back closure", "Tarnish-resistant coating", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "w15",
    slug: "pahadi-maangtika-gold",
    name: "Kumaoni Bridal Maangtika",
    pahadi_name: "कुमाऊँनी माँग टीका",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "heritage",
    material: "22KT Gold",
    badge: "New",
    images: ["/images/product-gold-maangtika.svg"],
    description: "A traditional Pahadi bridal Maangtika crafted in 22KT BIS hallmarked gold. The teardrop pendant at the centre echoes the sacred lakes of Kumaon — Sattal, Bhimtal, Naukuchiatal.",
    culturalNote: "In Uttarakhand, the Maangtika is the first ornament placed on a bride at her solah shringar — the sixteen adornments. Its weight is a blessing; its gold is a prayer.",
    details: ["22KT BIS Hallmarked Gold", "Weight: 8 grams approx.", "Adjustable chain length", "Teardrop pendant — hand engraved", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "w16",
    slug: "contemporary-maangtika-silver",
    name: "Aipan Silver Maangtika",
    pahadi_name: "ऐपण माँग टीका",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "silver",
    gender: "women",
    collection: "heritage",
    material: "925 Silver",
    badge: "New",
    images: ["/images/product-silver-maangtika.svg"],
    description: "A contemporary 925 silver Maangtika with Aipan folk-art engravings — the sacred geometric art of Kumaon. Light enough for everyday wear, meaningful enough for every occasion.",
    culturalNote: "Aipan patterns are drawn by Kumaoni women on auspicious days using rice flour and red clay. Here, they are etched permanently in sterling silver.",
    details: ["925 Sterling Silver — Oxidised finish", "Weight: 4.5 grams approx.", "Adjustable chain length", "Aipan geometric engravings", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "w17",
    slug: "pahadi-mangalsutra-gold",
    name: "Devbhoomi Mangalsutra",
    pahadi_name: "देवभूमि मंगलसूत्र",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "heritage",
    material: "22KT Gold",
    badge: "Bestseller",
    images: ["/images/product-gold-mangalsutra.svg"],
    description: "A sacred Pahadi Mangalsutra in 22KT BIS hallmarked gold — two black bead strings with a traditional Uttarakhand pendant inspired by the Kedarnath temple spire.",
    culturalNote: "In the Himalayan tradition, the Mangalsutra is tied by the groom himself around the bride's neck at the most sacred moment of the ceremony. This piece carries that weight — literally and spiritually.",
    details: ["22KT BIS Hallmarked Gold pendant", "Traditional black bead strings", "Chain length: 18 inches", "Kedarnath spire-inspired pendant", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "w18",
    slug: "modern-mangalsutra-diamond",
    name: "Nanda Peak Mangalsutra",
    pahadi_name: "नंदा शिखर मंगलसूत्र",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "gold",
    material: "Lab Grown Diamond in Gold",
    badge: "New",
    images: ["/images/product-diamond-mangalsutra.svg"],
    description: "A modern Mangalsutra for the contemporary Indian woman — an IGI-certified lab grown diamond solitaire set in 18KT gold, on a sleek single chain. Sacred, minimal, eternal.",
    details: ["IGI Certified Lab Grown Diamond — 0.3 CT", "18KT Gold chain + pendant", "Chain length: 16 inches — adjustable", "Modern single-chain design", "IGI Certificate included"],
    inStock: true,
  },
  {
    id: "w14",
    slug: "diamond-stud-earrings",
    name: "Tarini Diamond Studs",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "women",
    collection: "gold",
    material: "Lab Grown Diamond in Gold",
    badge: "Bestseller",
    images: ["/images/product-diamond-studs.jpg"],
    description: "Classic IGI-certified lab grown diamond stud earrings in 18KT gold. The perfect combination of timeless elegance and modern ethics.",
    details: ["IGI Certified Lab Grown Diamonds", "Total carat: 0.8 CT", "18KT Gold setting", "Screw-back closure", "IGI Certificate included"],
    inStock: true,
  },
  // ── Modern Silver Collection ──────────────────────────────────────────────
  {
    id: "ws1", slug: "arc-minimal-silver-necklace", name: "Binsar Arc Necklace",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women",
    collection: "silver", material: "925 Silver", badge: "New",
    images: ["/images/product-silver-arc-necklace.svg"],
    description: "A sleek arc pendant on a slim 925 silver chain. Architectural minimalism meets everyday luxury — the chain you never take off.",
    details: ["925 Sterling Silver", "Weight: 3.8 grams", "18-inch adjustable chain", "Tarnish-resistant finish", "Certificate of Authenticity"],
    inStock: true,
  },
  {
    id: "ws2", slug: "liquid-stack-ring-set", name: "Trishul Stack Rings",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women",
    collection: "silver", material: "925 Silver", badge: "Trending",
    images: ["/images/product-silver-stack-rings.svg"],
    description: "Three ultra-thin 925 silver rings designed to stack. Wear together or separately — fluid form, mirror finish, modern statement.",
    details: ["925 Sterling Silver — Set of 3", "Weight: 4.2 grams total", "Available in sizes 5-10", "High-polish finish", "Certificate of Authenticity"],
    inStock: true, sizes: ["5","6","7","8","9","10"],
  },
  {
    id: "ws3", slug: "vertex-bar-silver-earrings", name: "Devidhar Bar Earrings",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women",
    collection: "silver", material: "925 Silver", badge: "New",
    images: ["/images/product-silver-bar-earrings.svg"],
    description: "Clean geometric bar earrings in brushed 925 silver. Architectural lines, modern attitude — from boardroom to evening in one look.",
    details: ["925 Sterling Silver — Brushed finish", "Weight: 3.1 grams", "Push-back stud closure", "35mm drop", "Certificate of Authenticity"],
    inStock: true,
  },
  {
    id: "ws4", slug: "orbit-cuff-silver-bracelet", name: "Nanda Orbit Cuff",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women",
    collection: "silver", material: "925 Silver", badge: "Bestseller",
    images: ["/images/product-silver-orbit-cuff.svg"],
    description: "A bold open-ended 925 silver cuff with orbital texture — smooth, sculptural, instantly contemporary. The statement piece for every wrist.",
    details: ["925 Sterling Silver", "Weight: 18 grams", "Open cuff — adjustable fit", "Width: 12mm", "Certificate of Authenticity"],
    inStock: true,
  },
  {
    id: "ws5", slug: "horizon-crescent-pendant", name: "Chandra Crescent Pendant",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women",
    collection: "silver", material: "925 Silver", badge: "New",
    images: ["/images/product-silver-crescent.svg"],
    description: "A refined crescent moon pendant on a delicate 925 silver rolo chain. Minimal, celestial, and effortlessly contemporary.",
    details: ["925 Sterling Silver", "Weight: 4.5 grams", "16-inch chain + 2-inch extender", "Mirror-polished pendant", "Certificate of Authenticity"],
    inStock: true,
  },
  {
    id: "ws6", slug: "chainlink-hoop-earrings", name: "Devbhoomi Hoop Earrings",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women",
    collection: "silver", material: "925 Silver", badge: "Trending",
    images: ["/images/product-silver-chainlink-hoops.svg"],
    description: "Oversized chain-link hoops in 925 sterling silver — bold, modern, endlessly versatile. The hoop reimagined for the contemporary woman.",
    details: ["925 Sterling Silver", "Weight: 5.8 grams", "40mm diameter", "Click-back closure", "Certificate of Authenticity"],
    inStock: true,
  },
  {
    id: "ws7", slug: "fluid-link-anklet-silver", name: "Pahadi Payal Anklet",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women",
    collection: "silver", material: "925 Silver", badge: "New",
    images: ["/images/product-silver-anklet.svg"],
    description: "A fluid chain-link 925 silver anklet with a minimalist clasp. Lightweight, tarnish-resistant, and perfect for year-round wear.",
    details: ["925 Sterling Silver", "Weight: 5.2 grams", "9.5-inch adjustable", "Lobster clasp", "Certificate of Authenticity"],
    inStock: true,
  },
  {
    id: "ws8", slug: "pearl-drop-modern-earrings", name: "Saryu Pearl Drops",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women",
    collection: "silver", material: "925 Silver", badge: "Bestseller",
    images: ["/images/product-silver-pearl-drops.svg"],
    description: "Freshwater pearls suspended from sleek 925 silver bars — a modern take on the classic drop. Understated luxury for every occasion.",
    details: ["925 Sterling Silver + Freshwater Pearl", "Weight: 4.8 grams", "28mm drop", "Push-back closure", "Certificate of Authenticity"],
    inStock: true,
  },
  {
    id: "ws9", slug: "negative-space-silver-ring", name: "Aakash Open Band Ring",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women",
    collection: "silver", material: "925 Silver", badge: "New",
    images: ["/images/product-silver-void-ring.svg"],
    description: "An architectural open-form ring in 925 silver with cutout negative space design. Where sculpture meets jewellery.",
    details: ["925 Sterling Silver", "Weight: 5.1 grams", "Open adjustable band", "Brushed + polished contrast", "Certificate of Authenticity"],
    inStock: true, sizes: ["5","6","7","8","9","10"],
  },
  {
    id: "ws10", slug: "mesh-silver-bracelet-modern", name: "Kailash Weave Cuff",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "women",
    collection: "silver", material: "925 Silver", badge: "Trending",
    images: ["/images/product-silver-mesh-bracelet.svg"],
    description: "A woven mesh 925 silver bracelet with a modern box clasp. Flexible, featherlight, and impossibly elegant on the wrist.",
    details: ["925 Sterling Silver Mesh", "Weight: 12 grams", "7.5 inch length", "Box clasp with safety", "Certificate of Authenticity"],
    inStock: true,
  },
]

// ─── Men's Products ───────────────────────────────────────────────────────────

export const menProducts: Product[] = [
  {
    id: "m1",
    slug: "himalayan-silver-kada",
    name: "Himalayan Silver Kada",
    pahadi_name: "पर्वत कड़ा",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "silver",
    gender: "men",
    collection: "men",
    material: "925 Silver",
    badge: "Bestseller",
    images: ["/images/product-men-kada.svg"],
    description: "A bold 925 sterling silver kada bracelet with hammered texture, inspired by the rough terrain of the Himalayas. Designed to be worn daily, grows more beautiful with age.",
    culturalNote: "The Kada has deep roots in Uttarakhand warrior tradition — worn by men of the Rajput communities of Garhwal as a symbol of strength and protection.",
    details: ["925 Sterling Silver — Hammered finish", "Weight: 35 grams approx.", "Inner diameter: 2.6 inches", "Unisex sizing — fits most adult wrists", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "m2",
    slug: "men-chain-silver-bold",
    name: "Badrinath Anchor Chain",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "silver",
    gender: "men",
    collection: "men",
    material: "925 Silver",
    badge: "New",
    images: ["/images/product-men-anchor-chain.svg"],
    description: "A heavy-gauge 925 sterling silver anchor chain — bold, masculine, built to last. The anchor motif connects to Uttarakhand's Bhotiyas, traditionally great travellers.",
    details: ["925 Sterling Silver", "Weight: 28 grams approx.", "Chain width: 4mm", "Chain length: 22 inches", "Lobster clasp", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "m3",
    slug: "men-gold-ring-signet",
    name: "Devta Signet Ring",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "men",
    collection: "men",
    material: "22KT Gold",
    badge: "New",
    images: ["/images/product-men-signet-ring.svg"],
    description: "A bold 22KT gold signet ring with a flat face engraved with a geometric Mandana motif from Uttarakhand's folk art tradition. The statement ring every man deserves.",
    culturalNote: "Mandana is a sacred geometric folk art of the Kumaon hills, traditionally carved on temple walls and stone — we bring it to fine gold.",
    details: ["22KT BIS Hallmarked Gold", "Weight: 8.5 grams approx.", "Flat signet face — engravable", "Available in sizes 8-14", "Certificate of Authenticity included"],
    inStock: true,
    sizes: ["8", "9", "10", "11", "12", "13", "14"],
  },
  {
    id: "m4",
    slug: "men-diamond-pendant",
    name: "Summit Solitaire Pendant",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "men",
    collection: "men",
    material: "Lab Grown Diamond in Gold",
    badge: "New",
    images: ["/images/product-men-diamond-pendant.svg"],
    description: "A single IGI-certified round lab diamond set in a brushed 18KT white gold geometric pendant. Minimal, confident, and crafted for the modern Indian man.",
    details: ["IGI Certified Lab Grown Diamond", "0.5 Carat, VS1 Clarity", "Brushed 18KT White Gold pendant", "Sterling silver chain — 22 inches", "IGI Certificate included"],
    inStock: true,
  },
  {
    id: "m5",
    slug: "men-silver-ring-mountain",
    name: "Trishul Silver Ring",
    pahadi_name: "त्रिशूल अंगूठी",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "silver",
    gender: "men",
    collection: "men",
    material: "925 Silver",
    badge: "Trending",
    images: ["/images/product-men-trishul-ring.svg"],
    description: "A wide oxidised silver ring inspired by the three-pronged peak of Trishul mountain — one of the most iconic summits visible from Uttarakhand's Kumaon valleys.",
    culturalNote: "Trishul peak is considered sacred in Uttarakhand, the weapon of Mahadev himself. Wearing it is carrying Shiva's strength.",
    details: ["925 Sterling Silver — Oxidised finish", "Weight: 6 grams approx.", "Wide band — 8mm width", "Available in sizes 8-14", "Certificate of Authenticity included"],
    inStock: true,
    sizes: ["8", "9", "10", "11", "12", "13", "14"],
  },
  {
    id: "m6",
    slug: "men-gold-chain-box",
    name: "Kedarnath Box Chain",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "men",
    collection: "men",
    material: "22KT Gold",
    badge: "Bestseller",
    images: ["/images/product-men-curb-gold-chain.svg"],
    description: "A premium 22KT BIS hallmarked gold box chain — the signature men's chain in India. Heavy, lustrous, and built for daily wear or special occasions.",
    details: ["22KT BIS Hallmarked Gold", "Weight: 14 grams approx.", "Chain width: 3mm", "Chain length: 22 inches", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "m7",
    slug: "men-silver-bracelet-link",
    name: "Altitude Link Bracelet",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "silver",
    gender: "men",
    collection: "men",
    material: "925 Silver",
    badge: "Trending",
    images: ["/images/product-men-link-bracelet.svg"],
    description: "A heavy-gauge linked 925 silver bracelet — each link inspired by the ridgeline view of the Himalayan range from Chakrata in Uttarakhand.",
    details: ["925 Sterling Silver", "Weight: 22 grams approx.", "Link width: 10mm", "Length: 8.5 inches with clasp", "OT clasp", "Certificate of Authenticity included"],
    inStock: true,
  },
  {
    id: "m8",
    slug: "men-stud-earring-diamond",
    name: "Shikhar Solitaire Stud",
    price: 0,
    originalPrice: 0,
    discount: 0,
    category: "gold",
    gender: "men",
    collection: "men",
    material: "Lab Grown Diamond in Gold",
    badge: "New",
    images: ["/images/product-men-diamond-stud.svg"],
    description: "A single IGI-certified lab grown diamond stud in 18KT white gold. The modern man's most versatile jewellery piece — subtle, premium, effortless.",
    details: ["IGI Certified Lab Grown Diamond", "0.25 Carat, VVS1 Clarity", "18KT White Gold push-back stud", "Single earring (one piece)", "IGI Certificate included"],
    inStock: true,
  },
  // ── Modern Men's Additions ───────────────────────────────────────────────
  {
    id: "mm1", slug: "onyx-silver-pendant-men", name: "Mahakali Onyx Pendant",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men",
    collection: "men", material: "925 Silver", badge: "New",
    images: ["/images/product-men-onyx-pendant.svg"],
    description: "A matte black onyx stone set in a brushed 925 silver geometric frame. Dark, bold, and distinctly modern — for the man who commands the room.",
    details: ["925 Sterling Silver — Brushed", "Natural Onyx centre stone", "22-inch sterling silver chain", "Weight: 12 grams", "Certificate of Authenticity"],
    inStock: true,
  },
  {
    id: "mm2", slug: "rolo-chain-silver-men", name: "Garhwal Rolo Chain",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men",
    collection: "men", material: "925 Silver", badge: "Bestseller",
    images: ["/images/product-men-rolo-chain.svg"],
    description: "A thick 925 sterling silver rolo chain — bold, polished, timeless. The go-to chain for the man who knows quality when he wears it.",
    details: ["925 Sterling Silver — High Polish", "Weight: 32 grams", "Chain width: 5mm", "Length: 24 inches", "Certificate of Authenticity"],
    inStock: true,
  },
  {
    id: "mm3", slug: "gold-curb-chain-men", name: "Devprayag Gold Chain",
    price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "men",
    collection: "men", material: "22KT Gold", badge: "Trending",
    images: ["/images/product-men-curb-gold-chain.svg"],
    description: "A heavy flat curb chain in 22KT BIS hallmarked gold. The chain that needs nothing else — a signature piece for the man of substance.",
    details: ["22KT BIS Hallmarked Gold", "Weight: 18 grams", "Chain width: 4mm", "Length: 22 inches", "Certificate of Authenticity"],
    inStock: true,
  },
  {
    id: "mm4", slug: "oxidised-silver-ring-men", name: "Mandakini Shadow Band",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men",
    collection: "men", material: "925 Silver", badge: "New",
    images: ["/images/product-men-shadow-ring.svg"],
    description: "A heavy oxidised 925 silver band with a matte black finish and a subtle textured surface. Raw. Refined. Unmistakably masculine.",
    details: ["925 Sterling Silver — Oxidised matte", "Weight: 8 grams", "Width: 10mm", "Sizes 8–14", "Certificate of Authenticity"],
    inStock: true, sizes: ["8","9","10","11","12","13","14"],
  },
  {
    id: "mm5", slug: "serpentine-silver-bracelet-men", name: "Nag Serpentine Bracelet",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men",
    collection: "men", material: "925 Silver", badge: "Trending",
    images: ["/images/product-men-serpentine-bracelet.svg"],
    description: "A flat serpentine-link 925 silver bracelet — fluid and strong, just like the rivers of the Himalayan valleys. Wears like a second skin.",
    details: ["925 Sterling Silver", "Weight: 20 grams", "Width: 8mm", "8-inch length with OT clasp", "Certificate of Authenticity"],
    inStock: true,
  },
  {
    id: "mm6", slug: "matte-gold-ring-men", name: "Vishwakarma Forge Band",
    price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "men",
    collection: "men", material: "22KT Gold", badge: "New",
    images: ["/images/product-men-forge-ring.svg"],
    description: "A wide 22KT gold band with a forged matte finish and a single polished groove. Power in restraint — the ring that says everything without saying anything.",
    details: ["22KT BIS Hallmarked Gold", "Weight: 10 grams", "Width: 7mm", "Sizes 8–14", "Certificate of Authenticity"],
    inStock: true, sizes: ["8","9","10","11","12","13","14"],
  },
  {
    id: "mm7", slug: "lab-diamond-tennis-bracelet-men", name: "Summit Diamond Bracelet",
    price: 0, originalPrice: 0, discount: 0, category: "gold", gender: "men",
    collection: "men", material: "Lab Grown Diamond in Gold", badge: "Limited",
    images: ["/images/product-men-tennis-bracelet.svg"],
    description: "An IGI-certified lab diamond tennis bracelet in 18KT white gold. Subtle fire, maximum luxury — the bracelet that redefines men's fine jewellery.",
    details: ["IGI Certified Lab Grown Diamonds", "Total carat: 2.0 CT", "18KT White Gold setting", "Box clasp with safety", "IGI Certificate included"],
    inStock: true,
  },
  {
    id: "mm8", slug: "silver-thread-ring-set-men", name: "Panchachuli Ring Trio",
    price: 0, originalPrice: 0, discount: 0, category: "silver", gender: "men",
    collection: "men", material: "925 Silver", badge: "New",
    images: ["/images/product-men-meridian-rings.svg"],
    description: "Three slim 925 silver rings in varying widths — stack them all or pick one. Modern minimalism for the man who layers intentionally.",
    details: ["925 Sterling Silver — Set of 3", "Weights: 2g, 4g, 6g", "Sizes 8–14", "Polished + brushed contrast", "Certificate of Authenticity"],
    inStock: true, sizes: ["8","9","10","11","12","13","14"],
  },
]

// ─── All products combined ────────────────────────────────────────────────────

export const products: Product[] = [...womenProducts, ...menProducts]

// ─── Testimonials ─────────────────────────────────────────────────────────────

export const testimonials = [
  {
    id: 1,
    name: "Panchachuli Ring Trio",
    initial: "P",
    location: "Dehradun",
    product: "Ganga Galobandh Necklace",
    category: "Gold",
    rating: 5,
    text: "I wore the Galobandh at my cousin's wedding in Pauri. Every elder in the village recognised the design and asked where I got it. It felt like wearing a piece of my grandmother's memory.",
  },
  {
    id: 2,
    name: "Anjali Bisht",
    initial: "A",
    location: "Almora",
    product: "Kumaoni Pahunchi",
    category: "Silver",
    rating: 5,
    text: "The Aipan patterns on the Pahunchi are exactly what I see on the walls of my family home in Almora during Navratri. This is not a jewelry brand — this is our culture made wearable.",
  },
  {
    id: 3,
    name: "Meenakshi Rawat",
    initial: "M",
    location: "Mumbai",
    product: "Nanda Devi Solitaire",
    category: "Lab Diamond",
    rating: 5,
    text: "Living in Mumbai for 12 years, I sometimes forget where I come from. The Nanda Devi pendant reminds me every day. Extraordinary craftsmanship.",
  },
  {
    id: 4,
    name: "Rohit Chauhan",
    initial: "R",
    location: "Delhi",
    product: "Himalayan Silver Kada",
    category: "Men's Silver",
    rating: 5,
    text: "The Himalayan Kada is unlike anything I've worn before. Heavy, beautiful, and the craftsmanship is visible. Got compliments everywhere. Finally a jewellery brand for men that gets it.",
  },
  {
    id: 5,
    name: "Vikram Singh",
    initial: "V",
    location: "Bengaluru",
    product: "Devta Signet Ring",
    category: "Men's Gold",
    rating: 5,
    text: "The signet ring is stunning. The gold quality is top notch and the Mandana engraving is so unique — nobody else has anything like this. Arrived in beautiful packaging.",
  },
]

// ─── FAQ data ─────────────────────────────────────────────────────────────────

export const faqData = [
  {
    category: "Orders & Shipping",
    questions: [
      { q: "How long does delivery take?", a: "Standard delivery takes 5-7 business days across India. Express delivery (2-3 days) is available at checkout for an additional fee. All orders are fully insured during transit." },
      { q: "Do you ship internationally?", a: "Currently we ship only within India. International shipping is coming soon — sign up to our newsletter to be notified." },
      { q: "Is my order insured during shipping?", a: "Yes. Every order is 100% insured for its full value during transit. In the rare event of damage or loss, we replace the item at no additional cost." },
      { q: "Can I track my order?", a: "Yes. Once your order is dispatched, you'll receive a tracking link via email and SMS. You can also track in your account dashboard." },
    ],
  },
  {
    category: "Products & Certifications",
    questions: [
      { q: "What does BIS Hallmarked Gold mean?", a: "BIS (Bureau of Indian Standards) hallmarking is India's official gold purity certification. Our 22KT gold is 91.6% pure and our 18KT is 75% pure. Every hallmarked piece carries a unique HUID number you can verify on the BIS CARE app." },
      { q: "What is IGI Certified Lab Grown Diamond?", a: "IGI (International Gemological Institute) is the world's leading diamond certification body. Lab grown diamonds are real diamonds — same chemical composition as mined diamonds — grown in controlled lab environments. They are ethically sourced and cost 60-80% less than mined diamonds." },
      { q: "Is your 925 Silver genuine and not plated?", a: "Yes. All our silver jewellery is solid 925 sterling silver (92.5% pure silver). We never use silver plating. Each piece carries a 925 hallmark stamp you can see on the jewellery itself." },
      { q: "What is 925 sterling silver?", a: "925 sterling silver is an alloy of 92.5% pure silver and 7.5% other metals (usually copper) for strength. It is the international standard for fine silver jewellery." },
    ],
  },
  {
    category: "Returns & Exchanges",
    questions: [
      { q: "What is your return policy?", a: "We offer 15-day easy returns on all items. The jewellery must be in its original condition and packaging. Return shipping is free for domestic orders." },
      { q: "Can I exchange for a different size?", a: "Yes. Ring size exchanges are free within 30 days. If the size you need is in stock, we'll dispatch the replacement immediately on receipt of the return." },
      { q: "What if I receive a damaged item?", a: "Please contact us within 48 hours of delivery with photos of the damage. We'll arrange an immediate replacement or full refund — your choice." },
    ],
  },
  {
    category: "Jewellery Care",
    questions: [
      { q: "How do I care for my gold jewellery?", a: "Store in the pouch or box provided. Remove before swimming, exercising, or applying perfume/lotion. Clean gently with a soft cloth. Avoid harsh chemicals." },
      { q: "Will my silver jewellery tarnish?", a: "All 925 silver tarnishes naturally over time — this is normal. Store in an airtight zip-lock bag when not wearing. Clean with a silver polishing cloth. Wearing it daily actually slows tarnishing as skin oils protect the metal." },
      { q: "How do I clean my lab diamond jewellery?", a: "Soak in warm water with a few drops of mild dish soap, gently scrub with a soft toothbrush, rinse and pat dry. Avoid ultrasonic cleaners for prong-set stones." },
    ],
  },
]

// ─── Helper functions ─────────────────────────────────────────────────────────

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products
  return products.filter((p) => p.category === category)
}

export function getProductsByGender(gender: "women" | "men" | "all"): Product[] {
  if (gender === "all") return products
  return products.filter((p) => p.gender === gender || p.gender === "unisex")
}

export function getProductsByCollection(collectionId: string): Product[] {
  return products.filter((p) => p.collection === collectionId)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && (p.category === product.category || p.gender === product.gender))
    .slice(0, limit)
}
